<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\build\Skies.Framework.Library.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.8" />
  </ItemGroup>

</Project>
